<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>soarunit</string>
	</array>
	<key>name</key>
	<string>SoarUnit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(setup)\s+({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.soarunit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.soarunit</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>setup block run before each test block</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.soarunit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.soar</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.soar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(test)\s+(.+)\s+({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.soarunit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.soarunit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.soarunit</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>test block</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.soarunit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.soar</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.soar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>end-of-line comments</string>
			<key>match</key>
			<string>(;\s*)?\#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.soar</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.soar</string>
		</dict>
		<key>quoted-string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>escaped-char</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.soarunit</string>
	<key>uuid</key>
	<string>aea98b91-6d27-4092-a4b2-9969e89af5f8</string>
</dict>
</plist>
