<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>soar</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>\}</string>
	<key>name</key>
	<string>Soar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([sg]p)\s+{([A-z0-9][A-z0-9*=$%?_/@:&amp;&gt;&lt;-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.soar</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.soar</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>production container</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>keyword.operator.soar</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#production</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>other braced containers, like smem --add {}</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>keyword.operator.soar</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#production</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.soar</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.soar</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>other functions</string>
			<key>match</key>
			<string>(add-wme|alias|allocate|capture-input|cd|chunk-name-format|cli|clog|command-to-file|default-wme-depth|dirs|echo-commands|echo|edit-production|epmem|excise|explain-backtraces|firing-counts|gds-print|gp-max|help|indifferent-selection|init-soar|internal-symbols|learn|load-library|ls|matches|max-chunks|max-dc-time|max-elaborations|max-goal-depth|max-memory-usage|max-nil-output-cycles|memories|multi-attributes|numeric-indifferent-mode|o-support-mode|pbreak|popd|port|predict|preferences|print|production-find|pushd|pwatch|pwd|rand|remove-wme|replay-input|rete-net|rl|run|save-backtraces|select|set-library-location|set-stop-phase|smem|soarnews|source|srand|stats|stop-soar|svs|timers|time|unalias|verbose|version|waitsnc|warnings|watch-wmes|watch|wma)\s+([^{]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.soar</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.soar</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>default aliases</string>
			<key>match</key>
			<string>(a|aw|chdir|ctf|set-default-depth|ex|eb|fc|gds_print|h|man|\?|inds|init|is|l|dir|pr|p|pc|wmes|varprint|topd|pw|step|d|e|rw|rn|sn|st|stop|ss|interrupt|un|w)\s+([^{]*)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>end of line comment</string>
			<key>match</key>
			<string>(;\s*)?\#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.soar</string>
		</dict>
		<key>escaped-character</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.soar</string>
		</dict>
		<key>int-constant</key>
		<dict>
			<key>match</key>
			<string>-?[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.soar</string>
		</dict>
		<key>production</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>docstring</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.soar</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped-character</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>comment</key>
					<string>quoted strings</string>
					<key>end</key>
					<string>\|</string>
					<key>name</key>
					<string>string.quoted.other.soar</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped-character</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>standard and scientific floats</string>
					<key>match</key>
					<string>[+-]?[0-9]\.[0-9]+[eE][-+]?[0-9]+[dDfF]?|[+-]?[0-9]*\.[0-9]*[dDfF]?</string>
					<key>name</key>
					<string>constant.numeric.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>integers</string>
					<key>match</key>
					<string>-?[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>flags</string>
					<key>match</key>
					<string>:(?:o-support|i-support|chunk|default|interrupt|template)</string>
					<key>name</key>
					<string>support.type.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>arrow</string>
					<key>match</key>
					<string>--&gt;</string>
					<key>name</key>
					<string>keyword.operator.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>math ops</string>
					<key>match</key>
					<string>\+-\*/</string>
					<key>name</key>
					<string>keyword.operator.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>variables</string>
					<key>match</key>
					<string>&lt;[A-Za-z0-9$%&amp;*+/:=?_&lt;&gt;-]+&gt;</string>
					<key>name</key>
					<string>variable.parameter.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>attributes</string>
					<key>match</key>
					<string>\^</string>
					<key>name</key>
					<string>variable.other.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>all braces, prefs, and minus</string>
					<key>match</key>
					<string>[()&lt;&gt;.=&amp;+|!~@-]</string>
					<key>name</key>
					<string>keyword.control.soar</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>comment</key>
					<string>curly braces nest conditions; need this to prevent from ending a production</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#production</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>condition type</string>
					<key>match</key>
					<string>state|impasse</string>
					<key>name</key>
					<string>keyword.operator.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>nil</string>
					<key>match</key>
					<string>nil</string>
					<key>name</key>
					<string>constant.language.soar</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>non-quoted string</string>
					<key>match</key>
					<string>[A-Za-z0-9$%&amp;*+/:=?_&gt;&lt;-]+</string>
					<key>name</key>
					<string>string.unquoted.soar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>scientific-float-constant</key>
		<dict>
			<key>match</key>
			<string>[+-]?[0-9]\.[0-9]+[eE][-+]?[0-9]+[dDfF]?</string>
			<key>name</key>
			<string>constant.numeric.soar</string>
		</dict>
		<key>standard-float-constant</key>
		<dict>
			<key>comment</key>
			<string>standard|scientific</string>
			<key>match</key>
			<string>[-+]?[0-9]*\.[0-9]*[dDfF]?</string>
			<key>name</key>
			<string>constant.numeric.soar</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.soar</string>
	<key>uuid</key>
	<string>f4b14934-e34e-4a57-80b0-576e298cb1e7</string>
</dict>
</plist>
